# This is a basic workflow to help you get started with Actions

name: frontend-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Environment
env:
  NODE_VERSION: 16.14.0
  IMAGE_REPO_NAME: my-frontend-app
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    name: LINT JOB
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
    
